FROM node:20-alpine
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-workspace.yaml ./
COPY apps/api/package.json ./apps/api/
COPY packages/config/package.json ./packages/config/
RUN pnpm install
COPY . .
WORKDIR /app/apps/api
CMD ["pnpm", "dev"]